# Generated by Django 4.1.1 on 2022-09-12 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(error_messages={'unique': 'A user with this email already exists.'}, help_text="The user's email acts as the username.", max_length=255, unique=True, verbose_name='Email')),
                ('name', models.CharField(blank=True, help_text='Full name', max_length=255, verbose_name='Name')),
                ('is_staff', models.BooleanField(default=False, help_text='True if the user has access to the admin page.', verbose_name='Has Admin Access?')),
                ('country_of_residence', models.CharField(blank=True, max_length=255, verbose_name='Country of residence')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ('email',),
            },
        ),
    ]
