# Generated by Django 4.1.1 on 2022-09-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_coinaddress_final_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinaddress',
            name='final_balance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='coinaddress',
            name='total_received',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='coinaddress',
            name='total_sent',
            field=models.IntegerField(),
        ),
    ]
