# Generated by Django 4.1.1 on 2022-09-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_coinaddress_final_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinaddress',
            name='address',
            field=models.CharField(max_length=35, unique=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='coinaddress',
            name='address_hash',
            field=models.CharField(max_length=160, unique=True, verbose_name='Address Hash'),
        ),
    ]
