# Generated by Django 4.1.1 on 2022-09-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_coinaddress_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinaddress',
            name='address_hash',
            field=models.CharField(blank=True, max_length=160, unique=True, verbose_name='Address Hash'),
        ),
    ]
