# Generated by Django 4.1.1 on 2022-09-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_coinaddress_address_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinaddress',
            name='address_hash',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Address Hash'),
        ),
    ]
