# Generated by Django 4.1.1 on 2022-09-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_coinaddress_address_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_hash', models.CharField(max_length=255, unique=True, verbose_name='Tx hash')),
                ('fee', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('block_index', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
