# Generated by Django 4.1.1 on 2022-09-12 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinaddress',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.coinaddress'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.IntegerField(),
        ),
    ]
